spring.application.name=api

# URL de conexão com o banco de dados MariaDB.
# localhost = banco rodando na própria máquina
# 3306 = porta padrão do MariaDB/MySQL
# seu_banco = nome da base de dados criada
spring.datasource.url=jdbc:mariadb://localhost:3306/api

# Nome do usuário do banco de dados
spring.datasource.username=root

# Senha do usuário do banco de dados
spring.datasource.password=

# Driver JDBC usado para conectar no MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Dialeto do banco, para o Hibernate gerar comandos SQL compatíveis com MariaDB
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Define o comportamento da estrutura do banco
# update = cria ou atualiza tabelas automaticamente sem apagar os dados
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL executados pela aplicação
spring.jpa.show-sql=true

# Formata o SQL exibido no console para facilitar a leitura
spring.jpa.properties.hibernate.format_sql=true
